### ISSUE TITLE
Still works beautifully!

### ISSUE THREAD

**Issue by MikePelton** [teichgraf/FluiDemo#1]
Hi Rene - not an issue - more of a "thank you" couldn't see how else to get in touch. Just stumbled on this and built it under VS 2019 Community and it works out of the box, and very well too!

**Comment by reneschulte** [comment]
Glad to hear this @MikePelton 
You can also get in touch via social media like Twitter @rschu or LinkedIn.
Great to hear it is still providing value for you.
